_wandb:
    value:
        cli_version: 0.22.2
        e:
            8ylyoamem2ugw7mz76b7t6h6alq7o6bz:
                args:
                    - --method_type
                    - vicddpm
                    - --dataset
                    - smos
                    - --batch_size
                    - "128"
                    - --num_workers
                    - "32"
                    - --microbatch
                    - "128"
                    - --save_interval
                    - "10_000"
                    - --max_step
                    - "100_000"
                    - --model_save_dir
                    - ./smos_model_10_22
                    - --lr_anneal_steps
                    - "80_000"
                codePath: train.py
                codePathLocal: train.py
                cpu_count: 56
                cpu_count_logical: 112
                cudaVersion: "12.4"
                disk:
                    /:
                        total: "32212254720"
                        used: "10275176448"
                email: 1512972802@qq.com
                executable: /root/miniconda3/bin/python
                git:
                    commit: 2c87c4bc0da64c3042d529350a3d144076d9ecfc
                    remote: git@github.com:lyklbw/my_ddpm.git
                gpu: NVIDIA A800 80GB PCIe
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A800 80GB PCIe
                      uuid: GPU-7109f415-be85-b44e-34df-b103ae925fc5
                host: autodl-container-0a974485ba-53e52fe7
                memory:
                    total: "1081314701312"
                os: Linux-4.19.90-2107.6.0.0192.8.oe1.bclinux.x86_64-x86_64-with-glibc2.35
                program: /root/autodl-tmp/my_ddpm/train.py
                python: CPython 3.12.3
                root: /root/autodl-tmp/my_ddpm
                startedAt: "2025-10-23T06:37:34.761199Z"
                writerId: 8ylyoamem2ugw7mz76b7t6h6alq7o6bz
        m: []
        python_version: 3.12.3
        t:
            "1":
                - 1
                - 9
                - 41
                - 103
            "2":
                - 1
                - 9
                - 41
                - 103
            "3":
                - 16
            "4": 3.12.3
            "5": 0.22.2
            "12": 0.22.2
            "13": linux-x86_64
batch_size:
    value: 32
learning_rate:
    value: 0.0001
