_wandb:
    value:
        cli_version: 0.22.2
        e:
            0gytapazky6ox49jj30kp8nq5q8657oa:
                codePath: wandb_test.py
                codePathLocal: wandb_test.py
                email: 1512972802@qq.com
                executable: /root/miniconda3/bin/python
                git:
                    commit: af03afb8d805c233cdbb2cf54e8d7845f00bf094
                    remote: git@github.com:lyklbw/my_ddpm.git
                host: autodl-container-0a974485ba-53e52fe7
                os: Linux-4.19.90-2107.6.0.0192.8.oe1.bclinux.x86_64-x86_64-with-glibc2.35
                program: /root/autodl-tmp/my_ddpm/wandb_test.py
                python: CPython 3.12.3
                root: /root/autodl-tmp/my_ddpm
                startedAt: "2025-10-21T03:21:33.231100Z"
                writerId: 0gytapazky6ox49jj30kp8nq5q8657oa
        m: []
        python_version: 3.12.3
        t:
            "3":
                - 2
                - 16
            "4": 3.12.3
            "5": 0.22.2
            "12": 0.22.2
            "13": linux-x86_64
architecture:
    value: CNN
dataset:
    value: CIFAR-100
epochs:
    value: 10
learning_rate:
    value: 0.02
